Running on desktop2:
stdin: is not a tty
Traceback (most recent call last):
  File "bin/train.py", line 25, in <module>
    from data.dataset import ImageDataset  # noqa
  File "/home/pmen/Shortcuts-Problem-in-Medical-Image-Analysis/shortcuts-chest-xray/bin/../data/dataset.py", line 6, in <module>
    from data.imgaug import GetTransforms
  File "/home/pmen/Shortcuts-Problem-in-Medical-Image-Analysis/shortcuts-chest-xray/bin/../data/imgaug.py", line 2, in <module>
    import torchvision.transforms as tfs
  File "/home/pmen/.conda/envs/CheXpert-env/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/pmen/.conda/envs/CheXpert-env/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/home/pmen/.conda/envs/CheXpert-env/lib/python3.7/site-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
    from .utils import _read_pfm, verify_str_arg
  File "/home/pmen/.conda/envs/CheXpert-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 22, in <module>
    import requests
  File "/home/pmen/.conda/envs/CheXpert-env/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/pmen/.conda/envs/CheXpert-env/lib/python3.7/site-packages/urllib3/__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2u  20 Dec 2019'. See: https://github.com/urllib3/urllib3/issues/2168
