Running on desktop18:
stdin: is not a tty
Activating chexpert environment...
Traceback (most recent call last):
  File "bin/test_model.py", line 150, in <module>
    main()
  File "bin/test_model.py", line 147, in main
    run(args)
  File "bin/test_model.py", line 117, in run
    ImageDataset(args.in_csv_path, cfg, mode='test'),
  File "/home/pmen/Shortcuts-Problem-in-Medical-Image-Analysis/shortcuts-chest-xray/bin/../data/dataset.py", line 23, in __init__
    idx_sensitive_attribute = header.index(cfg.get('sensitive_attribute'))
ValueError: 'Drain' is not in list
