Running on desktop22:
stdin: is not a tty
Activating chexpert environment...
Traceback (most recent call last):
  File "bin/test_model.py", line 165, in <module>
    main()
  File "bin/test_model.py", line 162, in main
    run(args)
  File "bin/test_model.py", line 127, in run
    images, labels, sensitive_label = next(iter(dataloader_test))
ValueError: not enough values to unpack (expected 3, got 2)
